#!/usr/bin/env python3
"""Extend FBE's vendored bundle with mod-aware data + sprites.

Background
----------

The Factorio Blueprint Editor (FBE) bundle vendored under
``studio/static/fbe/`` ships only ``__base__`` + ``__core__`` prototypes
(121 entities, 214 recipes, 19 fluids). It cannot render Space Age
entities (foundry, electromagnetic-plant, biochamber, recycler,
cryogenic-plant, agricultural-tower, asteroid-collector, etc.) and it
applies vanilla parameter values for entities the user has tweaked
through mods (e.g. AdjustableModule increases beacon module_slots from
2 to 5).

This tool patches FBE's ``data.json`` and copies the corresponding
PNG sprites out of the local Factorio install so the iframe preview
renders the user's actual mod set.

What it does
------------

1. Loads ``specs/data-raw-dump.json`` (the authoritative live dump from
   the user's exact enabled mod set, generated by ``factorio
   --dump-data``) and ``~/.factorio/mods/mod-list.json``.
2. Diffs the dump against ``studio/static/fbe/data/data.json`` to find
   entities/items/recipes/fluids that are missing from FBE.
3. For each missing prototype, copies the dump entry verbatim into
   ``data.json``. The dump entries are already in FBE-compatible shape
   (same key names, same filename schema with ``__base__/...`` prefixes).
4. For entities that already exist in FBE but have different values in
   the dump (modded ``module_slots``, ``allowed_effects``,
   ``distribution_effectivity``, etc.) overlays the modded values onto
   the FBE entry. The overlay is whitelist-driven so we don't disturb
   sprite/circuit-connector geometry.
5. Walks every newly-added or overlaid prototype to collect referenced
   PNG paths (``__space-age__/graphics/icons/foundry.png``, etc.) and
   copies the matching files from the local Factorio install
   (``~/.local/share/Steam/.../Factorio/data/<source>/``) or extracts
   them from mod zips at ``~/.factorio/mods/<mod>.zip``.
6. Patches FBE's bundled JS to load ``.png`` files directly instead of
   transcoding ``.basis`` (the upstream cloud bundle uses Basis Universal
   for compactness; we don't have ``basisu`` locally so we ship raw PNGs).
7. Writes a backup of the original ``data.json`` to ``data.json.upstream``
   on first run so the change is fully reversible.
8. Idempotent: re-running detects what's already done by checking a
   ``__factudio_extension__`` sentinel in the patched ``data.json``.

CLI
---

    python3 tools/extend_fbe_for_mods.py            # apply
    python3 tools/extend_fbe_for_mods.py --dry-run  # report only
    python3 tools/extend_fbe_for_mods.py --force    # reapply from upstream

The exit code is 0 on success, non-zero if any required input is
missing (no dump, no game install, no FBE bundle).
"""

from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import sys
import zipfile
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Iterable

# --------------------------------------------------------------------------
# Paths.
# --------------------------------------------------------------------------

REPO_ROOT = Path(__file__).resolve().parent.parent
SPECS_DIR = REPO_ROOT / "specs"
STUDIO_DIR = REPO_ROOT / "studio"
FBE_DIR = STUDIO_DIR / "static" / "fbe"
FBE_DATA = FBE_DIR / "data" / "data.json"
FBE_DATA_UPSTREAM = FBE_DIR / "data" / "data.json.upstream"
FBE_DATA_DIR = FBE_DIR / "data"
FBE_ASSETS_DIR = FBE_DIR / "assets"

DUMP_PATH = SPECS_DIR / "data-raw-dump.json"
MOD_LIST = Path.home() / ".factorio" / "mods" / "mod-list.json"
MODS_DIR = Path.home() / ".factorio" / "mods"

# Game install root (`<root>/data/<source>/...`). We try Steam first then
# the standalone install. If neither exists we fall back to the dump for
# data and warn that sprites may be missing.
GAME_DATA_CANDIDATES = [
    Path.home() / ".local/share/Steam/steamapps/common/Factorio/data",
    Path.home() / ".factorio/data",
    Path("/usr/share/factorio/data"),
]

SENTINEL_KEY = "__factudio_extension__"

# --------------------------------------------------------------------------
# Logging helpers.
# --------------------------------------------------------------------------


def log(msg: str) -> None:
    sys.stderr.write(f"[extend_fbe] {msg}\n")


def err(msg: str) -> None:
    sys.stderr.write(f"[extend_fbe] ERROR: {msg}\n")


# --------------------------------------------------------------------------
# Mod handling.
# --------------------------------------------------------------------------


def load_enabled_mods() -> list[str]:
    """Return the list of mods enabled in mod-list.json (in declaration order).

    Returns an empty list (with a warning) if the file is missing.
    """
    if not MOD_LIST.is_file():
        log(f"warning: {MOD_LIST} not found; no mod overlay will be applied")
        return []
    try:
        data = json.loads(MOD_LIST.read_text())
    except json.JSONDecodeError as e:
        err(f"could not parse {MOD_LIST}: {e}")
        return []
    out: list[str] = []
    for m in data.get("mods", []):
        if m.get("enabled"):
            out.append(m["name"])
    return out


def find_game_data_root() -> Path | None:
    for c in GAME_DATA_CANDIDATES:
        if c.is_dir() and (c / "base").is_dir():
            return c
    return None


# --------------------------------------------------------------------------
# Source resolution: __<source>__/<rel> -> on-disk path.
# --------------------------------------------------------------------------

# Source aliases. Some mods name their internal `__name__` differently
# from the mod-list entry. The canonical name is the one inside the
# `data/` tree on disk and inside mod zip filenames.
_SOURCE_ALIASES = {
    # No known aliases yet. Add here if a mod ships __foo__ in its
    # prototype paths but ships its zip as ``Foo``.
}


@dataclass
class SourceMap:
    """Where to look for a sprite source named ``__<key>__``.

    ``disk_root`` is a directory we copy from byte-for-byte
    (game DLC). ``zip_path`` is a mod .zip we extract from
    (``<zip_path>``::<mod_name>/<rel> by Factorio's convention).
    Either ``disk_root`` or ``zip_path`` may be set, never both.
    """

    key: str
    disk_root: Path | None = None
    zip_path: Path | None = None
    zip_inner_prefix: str | None = None  # e.g. "AdjustableModule_1.1.3"


def discover_sources(enabled_mods: list[str]) -> dict[str, SourceMap]:
    """Build a map ``__source__`` -> SourceMap for everything we can reach.

    Always covers ``__base__``, ``__core__``. Then every game DLC
    directory present in the install. Then every enabled mod whose zip
    we can find under ``~/.factorio/mods/``.
    """
    out: dict[str, SourceMap] = {}

    game = find_game_data_root()
    if game is not None:
        for sub in game.iterdir():
            if sub.is_dir():
                out[sub.name] = SourceMap(key=sub.name, disk_root=sub)
                # Also expose under aliased name.
                for alias, real in _SOURCE_ALIASES.items():
                    if real == sub.name:
                        out[alias] = SourceMap(key=sub.name, disk_root=sub)

    # Mods.
    for name in enabled_mods:
        if name in {"base", "core", "space-age", "quality", "elevated-rails"}:
            continue
        zp, prefix = _find_mod_zip(name)
        if zp is None:
            continue
        out[name] = SourceMap(key=name, zip_path=zp, zip_inner_prefix=prefix)

    return out


def _find_mod_zip(mod_name: str) -> tuple[Path | None, str | None]:
    """Find the highest-version zip for ``mod_name`` under MODS_DIR.

    Returns (zip_path, inner_prefix). The inner prefix is the top-level
    directory inside the zip, which Factorio mandates be
    ``<mod_name>_<version>`` (or sometimes just ``<mod_name>``).
    """
    if not MODS_DIR.is_dir():
        return None, None
    candidates: list[tuple[tuple[int, ...], Path]] = []
    for p in MODS_DIR.iterdir():
        if not p.suffix == ".zip":
            continue
        stem = p.stem  # e.g. AdjustableModule_1.1.3
        if not (stem == mod_name or stem.startswith(mod_name + "_")):
            continue
        ver_part = stem[len(mod_name) + 1:] if "_" in stem and stem != mod_name else "0"
        try:
            ver = tuple(int(x) for x in ver_part.split("."))
        except ValueError:
            ver = (0,)
        candidates.append((ver, p))
    if not candidates:
        return None, None
    candidates.sort()
    zp = candidates[-1][1]
    # Probe inner prefix.
    try:
        with zipfile.ZipFile(zp) as zf:
            top_dirs = {n.split("/", 1)[0] for n in zf.namelist() if "/" in n}
    except zipfile.BadZipFile:
        return zp, None
    if mod_name in top_dirs:
        return zp, mod_name
    # Look for <mod_name>_<version> form.
    for d in top_dirs:
        if d.startswith(mod_name + "_") or d == mod_name:
            return zp, d
    if len(top_dirs) == 1:
        return zp, next(iter(top_dirs))
    return zp, None


def resolve_sprite_bytes(ref: str, sources: dict[str, SourceMap]) -> bytes | None:
    """Return the raw bytes for a sprite reference like ``__source__/path.png``.

    Returns None if we cannot find it.
    """
    m = re.match(r"__([A-Za-z0-9_\-]+)__/(.+)$", ref)
    if not m:
        return None
    source, rel = m.group(1), m.group(2)

    sm = sources.get(source)
    if sm is None and source in _SOURCE_ALIASES:
        sm = sources.get(_SOURCE_ALIASES[source])
    if sm is None:
        return None

    if sm.disk_root is not None:
        candidate = sm.disk_root / rel
        if candidate.is_file():
            try:
                return candidate.read_bytes()
            except OSError:
                return None
        return None
    if sm.zip_path is not None:
        # Try a few inner-prefix variants.
        prefixes = [sm.zip_inner_prefix or sm.key, sm.key]
        try:
            with zipfile.ZipFile(sm.zip_path) as zf:
                names = set(zf.namelist())
                for prefix in prefixes:
                    if not prefix:
                        continue
                    candidate = f"{prefix}/{rel}"
                    if candidate in names:
                        return zf.read(candidate)
        except zipfile.BadZipFile:
            return None
    return None


# --------------------------------------------------------------------------
# Walking dump entries to find referenced PNGs.
# --------------------------------------------------------------------------

_REF_RE = re.compile(r"__[A-Za-z0-9_\-]+__/[^\"\\]+\.png")


def collect_png_refs(obj: Any) -> set[str]:
    """Return all ``__source__/path.png`` strings reachable from ``obj``."""
    blob = json.dumps(obj, separators=(",", ":"), default=str)
    return set(_REF_RE.findall(blob))


# --------------------------------------------------------------------------
# Categorisation.
# --------------------------------------------------------------------------

# Item-like prototype categories in the dump.
ITEM_LIKE = {
    "item",
    "capsule",
    "tool",
    "item-with-entity-data",
    "rail-planner",
    "spidertron-remote",
    "module",
    "ammo",
    "gun",
    "armor",
    "space-platform-starter-pack",
    "blueprint",
    "blueprint-book",
    "deconstruction-item",
    "upgrade-item",
    "copy-paste-tool",
    "selection-tool",
    "repair-tool",
}

# Entity types that FBE's renderer recognises (so adding entries makes a
# difference). This list is derived from
# `studio/static/fbe/assets/index-*.js` -- functions inside that bundle
# branch on `entity.type` to choose how to render.
RENDERABLE_TYPES = {
    "accumulator", "ammo-turret", "arithmetic-combinator", "artillery-turret",
    "artillery-wagon", "assembling-machine", "beacon", "boiler",
    "burner-generator", "cargo-landing-pad", "cargo-wagon",
    "constant-combinator", "container", "curved-rail-a", "curved-rail-b",
    "decider-combinator", "display-panel", "electric-energy-interface",
    "electric-pole", "electric-turret", "elevated-curved-rail-a",
    "elevated-curved-rail-b", "elevated-half-diagonal-rail",
    "elevated-straight-rail", "fluid-turret", "fluid-wagon", "furnace",
    "gate", "generator", "half-diagonal-rail", "heat-interface",
    "heat-pipe", "infinity-cargo-wagon", "infinity-container",
    "infinity-pipe", "inserter", "lab", "lamp", "land-mine",
    "lane-splitter", "legacy-curved-rail", "legacy-straight-rail",
    "linked-belt", "linked-container", "loader", "loader-1x1",
    "locomotive", "logistic-container", "market", "mining-drill",
    "offshore-pump", "pipe", "pipe-to-ground", "power-switch",
    "programmable-speaker", "proxy-container", "pump", "radar",
    "rail-chain-signal", "rail-ramp", "rail-signal", "rail-support",
    "reactor", "roboport", "rocket-silo", "selector-combinator",
    "simple-entity-with-force", "simple-entity-with-owner", "solar-panel",
    "splitter", "storage-tank", "straight-rail", "temporary-container",
    "train-stop", "transport-belt", "underground-belt", "valve", "wall",
    # Space-age types FBE's renderer also handles (verified via grep on the
    # bundle's switch tables):
    "agricultural-tower", "asteroid-collector", "cargo-bay",
    "fusion-generator", "fusion-reactor", "lightning-attractor",
    "space-platform-hub", "thruster",
}

# Entity-categorical fields the user's mods commonly tweak. We OVERLAY
# these from the dump onto the existing FBE entry without touching
# sprite/connector geometry.
OVERLAY_FIELDS_ENTITY = {
    "module_slots",
    "allowed_effects",
    "allowed_module_categories",
    "effect_receiver",
    "energy_usage",
    "energy_source",
    "crafting_speed",
    "crafting_categories",
    "max_health",
    "supply_area_distance",
    "distribution_effectivity",
    "distribution_effectivity_bonus_per_quality_level",
    "profile",
    "researching_speed",
    "science_pack_drain_rate_percent",
    "inputs",
    "neighbour_bonus",
    "max_energy_production",
    "fluid_usage_per_tick",
    "maximum_temperature",
    "result_inventory_size",
    "source_inventory_size",
    "input_fluid_box",
    "output_fluid_box",
    "fluid_boxes",
    "rocket_parts_required",
    "fast_replaceable_group",
}


def is_renderable_entity(entry: dict[str, Any]) -> bool:
    t = entry.get("type")
    if t not in RENDERABLE_TYPES:
        return False
    flags = entry.get("flags") or []
    if "hidden" in flags or "not-blueprintable" in flags:
        # Still keep these for completeness; they may show up in saved
        # blueprints from other users. Just skip "hidden" specifically
        # if also lacks placement.
        if not (
            "placeable-neutral" in flags
            or "placeable-player" in flags
            or "player-creation" in flags
        ):
            return False
    return True


def all_entities_in_dump(dump: dict[str, Any]) -> dict[str, dict[str, Any]]:
    """Flatten every entity-like prototype in the dump, keyed by name.

    If two categories share a name (rare), the first wins.
    """
    out: dict[str, dict[str, Any]] = {}
    for cat, items in dump.items():
        if not isinstance(items, dict):
            continue
        if not items:
            continue
        sample = next(iter(items.values()))
        if not isinstance(sample, dict):
            continue
        sample_type = sample.get("type")
        if sample_type != cat:
            continue
        if cat not in RENDERABLE_TYPES:
            continue
        for n, e in items.items():
            if not isinstance(e, dict):
                continue
            if not is_renderable_entity(e):
                continue
            if n in out:
                continue
            out[n] = e
    return out


def all_items_in_dump(dump: dict[str, Any]) -> dict[str, dict[str, Any]]:
    out: dict[str, dict[str, Any]] = {}
    for cat in ITEM_LIKE:
        if cat in dump and isinstance(dump[cat], dict):
            for n, e in dump[cat].items():
                if isinstance(e, dict) and n not in out:
                    out[n] = e
    return out


def all_recipes_in_dump(dump: dict[str, Any]) -> dict[str, dict[str, Any]]:
    return {n: e for n, e in (dump.get("recipe") or {}).items() if isinstance(e, dict)}


def all_fluids_in_dump(dump: dict[str, Any]) -> dict[str, dict[str, Any]]:
    return {n: e for n, e in (dump.get("fluid") or {}).items() if isinstance(e, dict)}


# --------------------------------------------------------------------------
# Bundle PNG-load patch.
# --------------------------------------------------------------------------

# The upstream FBE bundle does
#     `/fbe/data/${i.replace(".png",".basis")}`
# which assumes sprite atlases were pre-converted to Basis Universal.
# We don't have basisu, so we ship raw PNGs and patch the bundle to load
# `.png` directly. We replace the substring with one of the same length so
# byte offsets and sourcemaps stay valid.
_BUNDLE_PATCH_OLD = '.replace(".png",".basis")'
_BUNDLE_PATCH_NEW = '.replace(".png",".png"  )'  # same length; no-op
assert len(_BUNDLE_PATCH_OLD) == len(_BUNDLE_PATCH_NEW), "patch must preserve byte length"


def patch_fbe_bundle(dry_run: bool) -> tuple[int, list[Path]]:
    """Patch every JS asset under FBE_ASSETS_DIR. Returns (count, files)."""
    if not FBE_ASSETS_DIR.is_dir():
        return 0, []
    patched = 0
    touched: list[Path] = []
    for p in FBE_ASSETS_DIR.glob("*.js"):
        try:
            text = p.read_text(encoding="utf-8")
        except OSError:
            continue
        if _BUNDLE_PATCH_OLD not in text:
            continue
        new_text = text.replace(_BUNDLE_PATCH_OLD, _BUNDLE_PATCH_NEW)
        if dry_run:
            patched += 1
            touched.append(p)
            continue
        # Back up exactly once per file.
        backup = p.with_suffix(p.suffix + ".upstream")
        if not backup.exists():
            backup.write_text(text, encoding="utf-8")
        p.write_text(new_text, encoding="utf-8")
        patched += 1
        touched.append(p)
    return patched, touched


# --------------------------------------------------------------------------
# Sprite copy.
# --------------------------------------------------------------------------


def copy_sprite(ref: str, sources: dict[str, SourceMap], dry_run: bool) -> str:
    """Copy ``__source__/path.png`` to FBE_DIR/data/__source__/path.png.

    Returns one of: ``"copied"``, ``"exists"``, ``"missing-source"``,
    ``"missing-file"``, ``"skipped"``.
    """
    m = re.match(r"__([A-Za-z0-9_\-]+)__/(.+)$", ref)
    if not m:
        return "skipped"
    source_dir = f"__{m.group(1)}__"
    rel = m.group(2)
    dest = FBE_DATA_DIR / source_dir / rel
    if dest.is_file() and dest.stat().st_size > 0:
        return "exists"
    data = resolve_sprite_bytes(ref, sources)
    if data is None:
        if m.group(1) not in sources and m.group(1) not in _SOURCE_ALIASES:
            return "missing-source"
        return "missing-file"
    if dry_run:
        return "copied"
    dest.parent.mkdir(parents=True, exist_ok=True)
    tmp = dest.with_suffix(dest.suffix + ".part")
    tmp.write_bytes(data)
    tmp.replace(dest)
    return "copied"


# --------------------------------------------------------------------------
# Main extension routine.
# --------------------------------------------------------------------------


@dataclass
class ExtendStats:
    entities_added: list[str] = field(default_factory=list)
    entities_overlaid: list[tuple[str, dict[str, Any]]] = field(default_factory=list)
    items_added: int = 0
    recipes_added: int = 0
    fluids_added: int = 0
    sprites_copied: int = 0
    sprites_exists: int = 0
    sprites_missing: int = 0
    sprites_missing_files: list[str] = field(default_factory=list)
    bundle_files_patched: int = 0
    sources_used: list[str] = field(default_factory=list)


def overlay_diff(fbe_entry: dict[str, Any], dump_entry: dict[str, Any]) -> dict[str, Any]:
    """Return whitelist-driven diff dump->fbe for OVERLAY_FIELDS_ENTITY."""
    out: dict[str, Any] = {}
    for f in OVERLAY_FIELDS_ENTITY:
        if f in dump_entry and dump_entry[f] != fbe_entry.get(f):
            out[f] = {"old": fbe_entry.get(f), "new": dump_entry[f]}
    return out


def extend(dump: dict[str, Any], fbe: dict[str, Any], sources: dict[str, SourceMap],
           dry_run: bool, force: bool) -> ExtendStats:
    stats = ExtendStats()
    stats.sources_used = sorted(sources.keys())

    fbe_entities = fbe.setdefault("entities", {})
    fbe_items = fbe.setdefault("items", {})
    fbe_recipes = fbe.setdefault("recipes", {})
    fbe_fluids = fbe.setdefault("fluids", {})

    dump_entities = all_entities_in_dump(dump)
    dump_items = all_items_in_dump(dump)
    dump_recipes = all_recipes_in_dump(dump)
    dump_fluids = all_fluids_in_dump(dump)

    # Sprites we need to copy. Collected as we go.
    sprite_refs: set[str] = set()

    # 1. Entities.
    for name, dentry in dump_entities.items():
        if name in fbe_entities:
            # Overlay modded values onto existing FBE entry. We keep
            # FBE's vanilla sprite/circuit-connector geometry untouched
            # because re-deriving those from the dump can desync against
            # the visible PixiJS atlas slicing.
            diff = overlay_diff(fbe_entities[name], dentry)
            if diff:
                if not dry_run:
                    for f in diff:
                        fbe_entities[name][f] = dentry[f]
                stats.entities_overlaid.append((name, diff))
            continue
        # Brand-new entity: copy wholesale.
        if not dry_run:
            fbe_entities[name] = dentry
        stats.entities_added.append(name)
        sprite_refs.update(collect_png_refs(dentry))

    # 2. Items.
    for name, dentry in dump_items.items():
        if name in fbe_items:
            continue
        if not dry_run:
            fbe_items[name] = dentry
        stats.items_added += 1
        sprite_refs.update(collect_png_refs(dentry))

    # 3. Recipes.
    for name, dentry in dump_recipes.items():
        if name in fbe_recipes:
            continue
        if not dry_run:
            fbe_recipes[name] = dentry
        stats.recipes_added += 1
        sprite_refs.update(collect_png_refs(dentry))

    # 4. Fluids.
    for name, dentry in dump_fluids.items():
        if name in fbe_fluids:
            continue
        if not dry_run:
            fbe_fluids[name] = dentry
        stats.fluids_added += 1
        sprite_refs.update(collect_png_refs(dentry))

    # 5. Copy sprites.
    for ref in sorted(sprite_refs):
        kind = copy_sprite(ref, sources, dry_run)
        if kind == "copied":
            stats.sprites_copied += 1
        elif kind == "exists":
            stats.sprites_exists += 1
        elif kind in ("missing-file", "missing-source"):
            stats.sprites_missing += 1
            if len(stats.sprites_missing_files) < 50:
                stats.sprites_missing_files.append(ref)

    # 6. Sentinel. Reflects the patched-vs-upstream delta as observed in
    #    THIS run -- on the second run nothing should change so the
    #    sentinel is the authoritative final state. We always re-derive
    #    the totals by counting against data.json.upstream so the values
    #    are stable across re-runs (idempotent in the strict sense).
    if not dry_run:
        upstream_counts = _upstream_counts()
        cur_entities = len(fbe_entities)
        cur_items = len(fbe_items)
        cur_recipes = len(fbe_recipes)
        cur_fluids = len(fbe_fluids)
        # Overlaid counts from this run (overlays don't accumulate; we
        # just persist the count from the most recent diff).
        # If nothing changed (re-run), the previous overlaid count is
        # still authoritative -- preserve it.
        existing = fbe.get(SENTINEL_KEY) or {}
        overlaid_count = (
            len(stats.entities_overlaid)
            if stats.entities_overlaid
            else int(existing.get("entities_overlaid") or 0)
        )
        sprites_copied_total = stats.sprites_copied + stats.sprites_exists
        fbe[SENTINEL_KEY] = {
            "version": 3,
            "entities_added": max(0, cur_entities - upstream_counts.get("entities", 0)),
            "entities_overlaid": overlaid_count,
            "items_added": max(0, cur_items - upstream_counts.get("items", 0)),
            "recipes_added": max(0, cur_recipes - upstream_counts.get("recipes", 0)),
            "fluids_added": max(0, cur_fluids - upstream_counts.get("fluids", 0)),
            "sprites_copied": sprites_copied_total,
            "sprites_missing": stats.sprites_missing,
            "sources": sorted(sources.keys()),
        }

    return stats


def _upstream_counts() -> dict[str, int]:
    """Return prototype counts in the unmodified upstream data.json,
    so the sentinel can report `entities_added = current - upstream`.

    Falls back to baseline numbers (FBE 2025-10 build) if the backup
    is missing.
    """
    if FBE_DATA_UPSTREAM.is_file():
        try:
            up = json.loads(FBE_DATA_UPSTREAM.read_text())
            return {
                "entities": len(up.get("entities") or {}),
                "items": len(up.get("items") or {}),
                "recipes": len(up.get("recipes") or {}),
                "fluids": len(up.get("fluids") or {}),
            }
        except (OSError, json.JSONDecodeError):
            pass
    return {"entities": 121, "items": 251, "recipes": 214, "fluids": 19}


# --------------------------------------------------------------------------
# Top-level CLI.
# --------------------------------------------------------------------------


def already_extended(fbe: dict[str, Any]) -> bool:
    return SENTINEL_KEY in fbe


def load_fbe_data(force: bool) -> dict[str, Any]:
    """Load FBE data.json, restoring from the upstream backup if --force."""
    if force and FBE_DATA_UPSTREAM.is_file():
        log("--force: restoring data.json from data.json.upstream")
        shutil.copy2(FBE_DATA_UPSTREAM, FBE_DATA)
    return json.loads(FBE_DATA.read_text())


def write_fbe_data(fbe: dict[str, Any]) -> None:
    """Write data.json, preserving the existing upstream backup if any."""
    if not FBE_DATA_UPSTREAM.is_file():
        log(f"backing up upstream data.json to {FBE_DATA_UPSTREAM.relative_to(REPO_ROOT)}")
        shutil.copy2(FBE_DATA, FBE_DATA_UPSTREAM)
    tmp = FBE_DATA.with_suffix(FBE_DATA.suffix + ".part")
    tmp.write_text(json.dumps(fbe, separators=(",", ":")))
    tmp.replace(FBE_DATA)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="extend_fbe_for_mods",
        description="Extend FBE's bundled data.json with mod-aware entries + sprites.",
    )
    parser.add_argument("--dry-run", action="store_true",
                        help="don't write anything; just report what would change")
    parser.add_argument("--force", action="store_true",
                        help="reset data.json to the upstream backup before extending")
    parser.add_argument("--quiet", action="store_true",
                        help="reduce log spam (still prints the final summary)")
    args = parser.parse_args(argv)

    # Sanity checks.
    if not FBE_DATA.is_file():
        err(f"missing FBE bundle at {FBE_DATA}.\n"
            "Run `bash studio/setup_fbe.sh` first.")
        return 2
    if not DUMP_PATH.is_file():
        err(f"missing data dump at {DUMP_PATH}.\n"
            "Run `bash tools/dump_prototypes.sh` first.")
        return 2

    enabled_mods = load_enabled_mods()
    if not args.quiet:
        log(f"enabled mods: {len(enabled_mods)}")
    sources = discover_sources(enabled_mods)
    if not args.quiet:
        log(f"sprite sources discovered: {len(sources)}")
    game = find_game_data_root()
    if game is None:
        log("warning: no Factorio game install found; sprites for "
            "DLC entities (foundry, recycler, ...) will be missing")
    elif not args.quiet:
        log(f"game install: {game}")

    fbe = load_fbe_data(force=args.force)
    if already_extended(fbe) and not args.force:
        log("data.json already extended (sentinel present). Re-running to "
            "pick up any new prototypes; pass --force to reset to upstream.")

    log(f"loading dump: {DUMP_PATH}")
    dump = json.loads(DUMP_PATH.read_text())

    stats = extend(dump, fbe, sources, dry_run=args.dry_run, force=args.force)

    # Always patch the bundle (idempotent: already-patched bundles are
    # detected by the absence of the old substring).
    bundle_patched, touched = patch_fbe_bundle(dry_run=args.dry_run)
    stats.bundle_files_patched = bundle_patched
    if not args.quiet:
        for p in touched:
            log(f"patched bundle: {p.relative_to(FBE_DIR)}")

    if not args.dry_run:
        write_fbe_data(fbe)

    # Summary.
    print()
    print("Extension summary")
    print("-" * 60)
    print(f"  entities added:    {len(stats.entities_added)}")
    print(f"  entities overlaid: {len(stats.entities_overlaid)}")
    print(f"  items added:       {stats.items_added}")
    print(f"  recipes added:     {stats.recipes_added}")
    print(f"  fluids added:      {stats.fluids_added}")
    print(f"  sprites copied:    {stats.sprites_copied}")
    print(f"  sprites already:   {stats.sprites_exists}")
    print(f"  sprites missing:   {stats.sprites_missing}")
    print(f"  bundle JS patched: {stats.bundle_files_patched}")
    if stats.entities_overlaid:
        print()
        print("  Notable overlays (modded parameter changes):")
        for name, diff in stats.entities_overlaid[:8]:
            for f, vals in diff.items():
                old = vals["old"]
                new = vals["new"]
                if isinstance(old, list) or isinstance(new, list):
                    continue  # too noisy
                if isinstance(old, dict) or isinstance(new, dict):
                    continue
                print(f"    {name}.{f}: {old} -> {new}")
    if stats.sprites_missing_files:
        print()
        print("  Missing sprites (first 10):")
        for ref in stats.sprites_missing_files[:10]:
            print(f"    {ref}")
    if args.dry_run:
        print()
        print("  (dry-run: no files written)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
